if Quote.GetCustomField('R2QFlag').Content == 'Yes':
    for i in Product.GetContainerByName('AR_HCI_PHD_ProjectInputs2').Rows:
        #Trace.Write(str(i.Columns['USM Implementation'].Value)+"-----------PHDLabor-----000----->"+str(i.Columns['Graphics and Reports'].Value)+"-->"+str(i.Columns['Test Environment Installation and Setup'].Value)+"-->"+str(i.Columns['On-Site Installation'].Value)+"--->"+str(dir(i.ParentContainer)))
        for p in i.ParentContainer.Rows:
            i.GetColumnByName('USM Implementation').SetAttributeValue(str(p.GetColumnByName('USM Implementation').DisplayValue))
            i.Columns['USM Implementation'].Value=str(p.GetColumnByName('USM Implementation').DisplayValue)
            i.GetColumnByName('Graphics and Reports').SetAttributeValue(str(p.GetColumnByName('Graphics and Reports').DisplayValue))
            i.Columns['Graphics and Reports'].Value=str(p.GetColumnByName('Graphics and Reports').DisplayValue)
            i.GetColumnByName('Test Environment Installation and Setup').SetAttributeValue(str(p.GetColumnByName('Test Environment Installation and Setup').DisplayValue))
            i.Columns['Test Environment Installation and Setup'].Value=str(p.GetColumnByName('Test Environment Installation and Setup').DisplayValue)
            i.GetColumnByName('On-Site Installation').SetAttributeValue(str(p.GetColumnByName('On-Site Installation').DisplayValue))
            i.Columns['On-Site Installation'].Value=str(p.GetColumnByName('On-Site Installation').DisplayValue)
            i.GetColumnByName('Post-Go-Live Activities').SetAttributeValue(str(p.GetColumnByName('Post-Go-Live Activities').DisplayValue))
            i.Columns['Post-Go-Live Activities'].Value=str(p.GetColumnByName('Post-Go-Live Activities').DisplayValue)
            i.GetColumnByName('Post Delivery Support').SetAttributeValue(str(p.GetColumnByName('Post Delivery Support').DisplayValue))
            i.Columns['Post Delivery Support'].Value=str(p.GetColumnByName('Post Delivery Support').DisplayValue)
            #Trace.Write(str(p.GetColumnByName('USM Implementation').DisplayValue)+"-----------PHDLabor-----parent----->"+str(p.GetColumnByName('Graphics and Reports').DisplayValue)+"-->"+str(p.GetColumnByName('Test Environment Installation and Setup').DisplayValue)+"-->"+str(p.GetColumnByName('On-Site Installation').DisplayValue)+"--->"+str(dir(i.ParentContainer)))
        #Trace.Write(str(i.Columns['USM Implementation'].Value)+"-----------PHDLabor-----111----->"+str(i.Columns['Graphics and Reports'].Value)+"-->"+str(i.Columns['Test Environment Installation and Setup'].Value)+"-->"+str(i.Columns['On-Site Installation'].Value)+"--->"+str(i.Columns['Post-Go-Live Activities'].Value)+"--->"+str(i.Columns['Post Delivery Support'].Value))
    for i in Product.GetContainerByName('AR_HCI_PHD_ProjectInputs1').Rows:
        for p in i.ParentContainer.Rows:
            i.GetColumnByName('Upgrade/Update-PHD').SetAttributeValue(str(p.GetColumnByName('Upgrade/Update-PHD').DisplayValue))
            i.Columns['Upgrade/Update-PHD'].Value=str(p.GetColumnByName('Upgrade/Update-PHD').DisplayValue)
            i.GetColumnByName('Upgrade/Update-Third Party Historian').SetAttributeValue(str(p.GetColumnByName('Upgrade/Update-Third Party Historian').DisplayValue))
            i.Columns['Upgrade/Update-Third Party Historian'].Value=str(p.GetColumnByName('Upgrade/Update-Third Party Historian').DisplayValue)
            #i.GetColumnByName('Scope of Work').SetAttributeValue(str(p.GetColumnByName('Scope of Work').DisplayValue))
            #i.Columns['Scope of Work'].Value=str(p.GetColumnByName('Scope of Work').DisplayValue)
            i.GetColumnByName('Scope of Work').SetAttributeValue('Yes')
            i.Columns['Scope of Work'].Value=str('Yes')
            i.GetColumnByName('Material Ordering').SetAttributeValue(str(p.GetColumnByName('Material Ordering').DisplayValue))
            i.Columns['Material Ordering'].Value=str(p.GetColumnByName('Material Ordering').DisplayValue)
            i.GetColumnByName('Staging Area Hardware and LAN Setup').SetAttributeValue(str(p.GetColumnByName('Staging Area Hardware and LAN Setup').DisplayValue))
            i.Columns['Staging Area Hardware and LAN Setup'].Value=str(p.GetColumnByName('Staging Area Hardware and LAN Setup').DisplayValue)
            i.GetColumnByName('Build and Configure').SetAttributeValue(str(p.GetColumnByName('Build and Configure').DisplayValue))
            i.Columns['Build and Configure'].Value=str(p.GetColumnByName('Build and Configure').DisplayValue)
        #Trace.Write(str(i.Columns['Upgrade/Update-PHD'].Value)+"-----------PHDLabor-----222----->"+str(i.Columns['Upgrade/Update-Third Party Historian'].Value)+"-->"+str(i.Columns['Scope of Work'].Value)+"-->"+str(i.Columns['Material Ordering'].Value)+"--->"+str(i.Columns['Staging Area Hardware and LAN Setup'].Value)+"-->"+str(i.Columns['Build and Configure'].Value))