accountname = Quote.GetCustomField('Account Name').Content
accountnamelist = ["Flowell Kft","Acuraflow SpA","AT-Marine Oy","August Storm GmbH & Co. KG","Bilfinger EMS GmbH","bnNetze GmbH","Caldeiras Industriais e Maritimas Eireli - HQ","Cavcon Inc","Central Pacific Controls LLC","Christian Bindemann Group of Companies GmbH & Co. KG","Circular SA","Control Cia Ltda","Control Distributed Trading Establishment fze","Controles Electricos del Costa Rica SA - Grupo CONELEC","Craigcor Distribution Co Pty Ltd","Creative Robotics Pvt Ltd","Daiwa Hanbai Co Ltd","DC Automation Ltd","Ecomatic AS","ELECTRA GRUP MUHENDISLIK ELEKTRIK TAAHHUT MEKANIK PANO IMALAT ITH IHR SAN VE TIC AS","Enercity AG","Enercity Netz GmbH","ETW Energietechnik GmbH","Euromekanik AB - HQ","Everest Automation Inc","Fluides Precision","Fluidic Ltd","Franklen Equipment Inc","Futuristic Technologies","GA Digital Ltd","Garlas Control SA","Gazomet Sp zoo","Gil Automations Ltd","Giza Systems and Distribution - HQ","GP Systems and Solutions Pvt. Ltd","Hanley Controls","Herpla Engineering Corp","Hormel Oy","Hyperion Systems Engineering Ltd","IAC Peru SAC","Icasa Ingenieria SA de CV","IKM Instrutek AS","IMAC Systems Inc","Ingenieria en Automatizacion y Control Ltda - IAC Ltda","INOMEC S.A. de C.V.","Instrumarket Inc","Koons Gas Measurement","Ladder Automation Solutions Pvt Ltd","Centum Controls Pvt Ltd","Madei Taas Industrial Controls Ltd","Manstock Engineering Co Pvt Ltd","MERCON Sp. z o.o.","Mustafa Sultan Science and Industry Co","NIC Instruments & Engineering (PTY) LTD","NS Automacao e Instrumentacao Ltda","Operaciones Internacionales SA","Pacific Industrial Corp - HQ","Petroleum Measurement Integrators Ltd","Plant Solutions Ltd","PUMPTECHNIQUE SIA","Pyrometer Systems Ltd","Quattro Global Services LLC dba Ferrum Energy","Sensorwell Vertriebs GesmbH","Sesa Elektronik San ve Tic as","Sifab AS","Sofcon Systems India Pvt Ltd","Solberg Elektro AS","Techon","TEN Thuringer Energienetze GmbH & Co KG","Universal Controls - HQ","Urban del Golfo","Vanasa Multigas Engenharia Industria e Comercio Ltda","Vizen Solutions","Wesernetz Bremen GmbH","World Ocean","Yedi Deniz","Ed Young Sales Co Inc","Equipos y Accesorios para Gas LP y Natural SA de CV - HQ","Imfluid Ltda","Industrial Manufacturing Technologies LLC","Safety Gear Store","Stadtwerke Wismar GmbH","SWTE Netz GmbH Co. KG","UMC International"]
accountnamevalidate = Quote.GetCustomField('Account_Validation').Content
#Trace.Write(accountnamevalidate)
if (accountname in accountnamelist):
    #Trace.Write("True")
    Quote.GetCustomField('Account_Validation').Content = "Yes"
else:
    #Trace.Write("False")
    Quote.GetCustomField('Account_Validation').Content = "No"
#Trace.Write("Name:{0}".format(accountnamevalidate))