Qtyofcab = Product.Attr("TPS_EX_QTY_New_Cabinates").GetValue()
if int(Qtyofcab)>0:
	Product.AllowAttr('TPS_EX_Cabinet_Depth_Size')
	Product.AllowAttr('TPS_EX_Power_Supply_Voltage')
	Product.AllowAttr('TPS_EX_Cabinet_Door_Type')
	Product.AllowAttr('TPS_EX_Cabinet_Keylock_Type')
	Product.AllowAttr('TPS_EX_Cabinet_Hinge_Type')
	Product.AllowAttr('TPS_EX_Cabinet_Thermostat_Required')
	Product.AllowAttr('TPS_EX_Cabinet_Base_Required')
	Product.AllowAttr('TPS_EX_Cabinet_Color')
	Product.Attr("TPS_EX_Power_Supply_Voltage").SelectValue("120V, 60 Hz")
else:
	Product.DisallowAttr('TPS_EX_Cabinet_Depth_Size')
	Product.DisallowAttr('TPS_EX_Power_Supply_Voltage')
	Product.DisallowAttr('TPS_EX_Cabinet_Door_Type')
	Product.DisallowAttr('TPS_EX_Cabinet_Keylock_Type')
	Product.DisallowAttr('TPS_EX_Cabinet_Hinge_Type')
	Product.DisallowAttr('TPS_EX_Cabinet_Thermostat_Required')
	Product.DisallowAttr('TPS_EX_Cabinet_Base_Required')
	Product.DisallowAttr('TPS_EX_Cabinet_Color')