if Product.Attr('CE_Scope_Choices').GetValue()=='HW/SW':
    Product.DisallowAttr('Header_04_open')
    Product.DisallowAttr('Header_04_close')
    Product.DisallowAttr('C300_Implementation_Methodology')
    Product.DisallowAttr('C300_GES_Location')
    Product.DisallowAttr('C300_Process_Type')
    Product.DisallowAttr('Number_of_Peer_PCDI')
    Product.DisallowAttr('Number_of_Peer_CDA')
    Product.DisallowAttr('Number_of_SCADA_Node_Types_for_C300')
    Product.DisallowAttr('Enter_total_count_of_Typicals/Prototypes (0-500)')
    Product.DisallowAttr('Input_Quality (User Requirement Specification)')
    Product.DisallowAttr('No_of_Complex_SCMs_per_Unit (0-100)')
    Product.DisallowAttr('No_of_Complex_Operations_per_Product (0-100)')
    Product.DisallowAttr('Percentage_for_Pre-FAT(0-100%)')