system = Product.GetContainerByName('List of Locations/Clusters/Network Groups')
ACE=Product.Attr('ACE Node Rack Mount Cabinet').GetValue()

count=count1= 0
if ACE > 0 :
    for i in system.Rows:
        #if i.IsSelected and i['Scope'] == 'HWSWLABOR' and TagParserProduct.ParseString('[LIKE](<*VALUE(CE_Selected_Products)*>,Experion Enterprise System)')=='1':
        I=i['List of Locations/Clusters/ Network Groups']
        Trace.Write((i['List of Locations/Clusters/ Network Groups']))
        count += 1
    Trace.Write(count)
    if count== 1:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2', 'Location/Cluster/Network Group3', 'Location/Cluster/Network Group 4', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count== 2:
        Product.DisallowAttrValues('ACE Node Cluster', 'Location/Cluster/Network Group3', 'Location/Cluster/Network Group 4', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==3:
        Product.DisallowAttrValues('ACE Node Cluster', 'Location/Cluster/Network Group 4', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==4:
        Product.DisallowAttrValues('ACE Node Cluster', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==5:
        Product.DisallowAttrValues('ACE Node Cluster', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==6:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==7:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Groupa', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==8:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==9:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==10:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==11:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==12:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==13:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==14:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==15:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==16:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==17:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==18:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==19:
       Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==20:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==21:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==22:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2q', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==23:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==24:
       Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==25:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==26:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==27:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==28:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==29:
         Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==30:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==31:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==32:
         Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==33:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==34:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==35:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==36:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==37:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==38:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==39:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==40:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==41:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==42:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==43:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==44:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==45:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==46:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==47:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    elif count==48:
        PProduct.DisallowAttrValues('ACE Node Cluster', 'Network Group 2qq', 'Network Group 2rr')
    elif count==49:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group 2rr')
    elif count==50:
        Product.AllowAttrValues('ACE Node Cluster', 'Network Group1', 'Network Group 2', 'Location/Cluster/Network Group3', 'Location/Cluster/Network Group 4', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')
    else:
        Product.DisallowAttrValues('ACE Node Cluster', 'Network Group1', 'Network Group 2', 'Location/Cluster/Network Group3', 'Location/Cluster/Network Group 4', 'Location/Cluster/Network Group 5', 'Location/Cluster/Network Group 6', 'Network Groupa', 'Network Group 2ss', 'Network Groupb', 'Network Groupc', 'Network Group 2d', 'Network Group 2f', 'Network Group 2g', 'Network Group 2h', 'Network Group 2i', 'Network Group 2j', 'Network Group 2k', 'Network Group 2l', 'Network Group 2m', 'Network Group 2n', 'Network Group 2o', 'Network Group 2q', 'Network Group 2p', 'Network Group 2r', 'Network Group 2s', 'Network Group 2t', 'Network Group 2u', 'Network Group 2v', 'Network Group 2w', 'Network Group 2x', 'Network Group 2y', 'Network Group 2z', 'Network Group 2aa', 'Network Group 2bb', 'Network Group 2cc', 'Network Group 2dd', 'Network Group 2ee', 'Network Group 2ff', 'Network Group 2gg', 'Network Group 2hh', 'Network Group 2ii', 'Network Group 2jj', 'Network Group 2kk', 'Network Group 2ll', 'Network Group 2mm', 'Network Group 2nn', 'Network Group 2oo', 'Network Group 2pp', 'Network Group 2qq', 'Network Group 2rr')