class SafetyManagerContainerColumns:
    rgNonR2QContColumn = {"SM_RG_Cabinet_Details_Cont": ["SM_DI_NAMUR_Switches_Adapter_UMC", "SM_DI_DORelay_Adapter_UMC", "SM_DI_Relay_resistor_Adapter_UMC", "SM_Shutdown_Input_DIO", "SM_Shutdown_Input_DIO_Redundant", "SM_Shutdown_Input_UIO", "SM_Shutdown_Input_UIO_Redundant", "SM_SDO_UIO_Unit_Load", "SM_SDO_UIO_DIO", "SM_SDO_UIO_UnitLoad", "SM_MCAR_Blank_Filler", "SM_Key_Switch_ModuleRequired", "SM_Conformally_Coated"], "SM_RG_Cabinet_Details_Cont_Left":["SM_RG_Percentage_SSM_Cabinet(0-100%)","SM_RG_RelayTypeForESD", "Extended_Temperature", "Distance_SM_SC_UIO/DIO_modules", "ELD_Module", "Fault_Contact_GIIS_Integration_Boards", "SIC_Length", "IOTA_Ethernet_Cable_Length", "Power_Supply", "Cabinet_Thermostat", "Cabinet_Feeder_Voltage", "Cabinet_Light", "Cabinet_Access", "Cabinet_IP_Rating"], "SM_SC_Universal_Safety_Cab_1_3M_Details_cont":["Power_Supply_Type", "CNM_SFP_Type","Number_of_SFP_0-500", "Number_of_Control_Network_Module_0-100", "Abu_Dhabi_Build_Loc", "External _24VDC_Terminal_Block", "Temperature_Monitoring", "IO_Redundancy", "Earth_Leakage_Detector_TELD", "Power_Supply_Redundancy", "Wire_Routing_Options", "Field_Termination_Assembly_for_PDIO", "Field_Termination_Assembly_for_PUIO", "Fiber_Optic_Extender","Ambient_Temperature_Range", "Cabinet_Material_Type_Ingress_Protection"],"SM_RG_ATEX Compliance_and_Enclosure_Type_Cont":["ATEX_Compliance"], "SM_RG_Universal_Safety_Cabinet_1.3M_Cont":["Specify_Identifier_Modifier_for_SM_SC_Universal_Safety_Cabinet", "UI_Identifier_Modifier_for_SM_SC_Universal_Safety_Cabinet", "Identifier_Modifier_for_SM_SC_Universal_Safety_Cabinet"]}
    
    rgContainersAndRows = {'SM_RG_IO_Count_Digital_Input_Cont':'Digital_Input_Type', 'SM_RG_IO_Count_Digital_Output_Cont':'Digital_Output_Type', 'SM_RG_IO_Count_Analog_Input_Cont':'Analog_Input_Type'}
    
    rgContainersAndColumns = {'SM_RG_IO_Count_Digital_Input_Cont':("SDI(1) 24Vdc with 5K Resistor DIO  (0-5000)", "SDI(1) 24Vdc with 5K Resistor UIO  (0-5000)", "SDI(1) 24Vdc Line Mon DIO (0-5000)", "SDI(1) 24Vdc Line Mon UIO  (0-5000)"), 'SM_RG_IO_Count_Digital_Output_Cont':("SDO(16) SIL 2/3 250Vac/Vdc COM DIO  (0-5000)", "SDO(16) SIL 2/3 250Vac/Vdc DIO  (0-5000)", "SDO(16) SIL 2/3 250Vac/Vdc COM UIO  (0-5000)", "SDO(16) SIL 2/3 250Vac/Vdc UIO   (0-5000)", "SDO(7) 24Vdc Line Mon UIO  (0-5000)", "SDO(4)24Vdc 2A UIO  (0-5000)", "SDO(2)24Vdc 1A UIO  (0-5000)"), 'SM_RG_IO_Count_Analog_Input_Cont':("SAI(1)FIRE 3-4 wire current  Sink UIO  (0-5000)", "SAI(1) GAS current  UIO  (0-5000)", "SAI(1)FIRE 3-4 wire current  UIO  (0-5000)", "SAI(1)FIRE 2 wire current  UIO   (0-5000)", "SDI(1) 24Vdc DIO  (0-5000)", "SDI(1)  24Vdc SIL3 P+F UIO  (0-5000)", "SDI(1)  24Vdc SIL2 P+F UIO  (0-5000)", "SDI(1) 24Vdc UIO  (0-5000)")}
    
    rgHideShowConcol = [{"SM_RG_Universal_Safety_Cabinet_1.3M_Cont":['Number_of_SM_SC_1.3M_Universal_Safety_Cabinets_(0-63)'], "SM_SC_Universal_Safety_Cab_1_3M_Details_cont":['S300', 'PUIO_Count', 'PDIO_Count']},{"SM_RG_Cabinet_Details_Cont":['SM_Percent_Installed_Spare_IO'], "SM_RG_Cabinet_Details_Cont_Left":['Marshalling_Option', 'SM_RG_RelayTypeForESD', 'SM_RG_Percentage_SSM_Cabinet(0-100%)']}]

    cgNonR2QContColumn = {"SM_CG_Cabinet_Details_Cont_Right":["DI_NAMUR_proximity_Switches_Adapter_UMC", "DI/DO_SIL2/3_Relay_Adapter_UMC", "DI_SIL1_Relay_5K_resistor_Adapter_UMC", "Shutdown_Input_DIO", 	"Shutdown_Input_DIO_Redundant", "Shutdown_Inpu_UIO", "Shutdown_Input_UIO_Redundant", "SDO_4_24Vdc2A_UIO_Unit_Load_1001mA_2000mA", "SDO_2_24Vdc1A_UIO_Unit_Load_501mA_1000mA", 					"SDO_24Vdc_500mA_UIO_DIO_UnitLoad1mA-500mA", "MCAR_Blank_Filler", "Key_Switch_Module_Required", "Conformally_Coated"], "SM_CG_Cabinet_Details_Cont_Left" : ["SM_CG_RelayTypeForESD", "Extended_Temperature", "Distance_SM_SC_UIO/DIO_modules", "ELD_Module", "Fault_Contact_GIIS_Integration_Boards", "SIC_Length", "IOTA_Ethernet_Cable_Length", "Power_Supply", "Cabinet_Thermostat", "Cabinet_Feeder_Voltage", "Cabinet_Light", "Cabinet_Access", "Cabinet_IP_Rating"]}

    cgContainersAndRows = {'SM_IO_Count_Digital_Input_Cont':'Digital Input Type', 'SM_IO_Count_Digital_Output_Cont':'Digital Output Type', 'SM_IO_Count_Analog_Input_Cont':'Analog Input Type'}

    cgContainersAndColumns = {'SM_IO_Count_Digital_Input_Cont':("SDI(1) 24Vdc with 5K Resistor UIO (0-5000)", "SDI(1) 24Vdc with 5K Resistor DIO (0-5000)", "SDI(1) 24Vdc Line Mon UIO (0-5000)", "SDI(1) 24Vdc Line Mon DIO (0-5000)"), 'SM_IO_Count_Digital_Output_Cont':('SDO(7) 24Vdc Line Mon UIO (0-5000)', 'SDO(16) SIL 2/3 250Vac/Vdc UIO (0-5000)', 'SDO(16) SIL 2/3 250Vac/Vdc COM UIO (0-5000)', 'SDO(16) SIL 2/3 250Vac/Vdc DIO (0-5000)', 'SDO(16) SIL 2/3 250Vac/Vdc COM DIO (0-5000)'), 'SM_IO_Count_Analog_Input_Cont':('SAI(1)FIRE 3-4 wire current Sink UIO (0-5000)', "SAI(1)FIRE 2 wire current UIO (0-5000)", 'SAI(1)FIRE 3-4 wire current UIO (0-5000)', 'SAI(1) GAS current UIO (0-5000)')}

    safetyManagerContainer = ['SM_Hardware_Builder_Station_Cont', 'SM_Hardware_Historian_Station_Cont', 'SM_Hardware_Simulation_Station_Cont']

    childProductScripts1 = ['PS_Default','OnProductRuleExecutionEnd','PS_Hide_Attr_Values','PS_populate_doc_param','PS_SM_Hide_Values','SM_System_PartSummary','PS_SM_SSE_Engineering_Labor_Container_Populate','PS_SM_Calculate_Labor_Hours','Show_Safety_Manager_Error_Deliverables','PS_Calc_Final_Hrs','final_hr','error_msg','PS_Populate_Prices','PS_System_LI_Part_Summary']

    childProduct1Scripts = ['PS_System_LI_Part_Summary']

    childProductScripts2 = ['PS_SM_CG_Part_Summary', 'PS_SM_CG_LI_Part_Summary']

    childProduct2Scripts = ['PS_SM_Hide_values', 'OnProductRuleExecutionEnd', 'PS_SM_Parts_components', 'PS_SM_CG_Component_Calcs', 'PS_SM_CG_IOTAs_Calcs', 'PS_SM_Sys_Cabinets_Qty', 'PS_License_run', 'PS_SM_CG_Part_Summary', 'PS_Populate_Total_IO_Points', 'PS_SM_IO_Cnt_Populate', 'PS_SM_CG_LI_Part_Summary']

    childProductScripts3 = ['PS_SM_RG_Part_Summary', 'PS_SM_RG_LI_Part_Summary'] #

    childProduct3Scripts = ['PS_Distance_SM_SC_UIO_DIO_modules', 'PS_SM_RG_Constraints', 'PS_Identifier_Modifier_Backend_String_Update', 'PS_Identifier_Modifier_Constraints', 'PS_SM_RG_ IOTAs_Component_Calcs', 'PS_SM_RG_Part_Components', 'PS_SM_RG_Component_Calcs', 'PS_SM_remote_Sys_Cabinets_Qty', 'PS_SM_RG_IMCode_validation', 'PS_Identifier_Modifier_Constraints_2', 'PS_SM_RG_Part_Summary', 'PS_SM_IO_Cnt_Cabinet_1.3', 'PS_SM_RG_LI_Part_Summary']


class UOCContainerColumns:
    nonR2QContColumn = {"UOC_Common_Questions_Cont":["UOC_Shielded_Terminal_Strip","UOC_IO_Filler_Module","UOC_Cluster","UOC_Starter_Kit","UOC_Starter_ Kit_with_Experion_License"],"UOC_Labor_Details":["UOC_Impl_Method_Labour","UOC_Ges_Location_Labour","UOC_Marshalling_Cabinet_Cont_Labour","UOC_Num_Peer_PCDI_Labour","UOC_Num_Peer_CDA_Labour","UOC_Num_Peer_to_Peer","UOC_Enter_Total_Count_Labour","UOC_Num_New_Typicals","UOC_Num_SCADA_Node_Type","UOC_Num_Complex_Loops_Labour","UOC_Num_ProfiNet_Devices_Labour","UOC_Num_ProfiNet_Devices_IO_Labour","UOC_Num_EtherNet_Devices_Labour","UOC_Num_EtherNet_Devices_IO_Labour","UOC_Input_Quality_Specific_Labour","UOC_Num_Complex_SCMs_Per_Unit_Labour","UOC_Num_Complex_Operations_Per_Product_Labour","UOC_Percentage_Pre_FAT","UOC_Num_ThirdParty_Serial_Scada"]}