default_flag = Product.Attr('Scada_default_check').GetValue()
if default_flag == '':
    Product.Attr('Scada_default_check').SelectValue('Yes')
    Product.Attr('Scada_Development_of_any_custom_applications').SelectValue('Yes, but it is familiar')
    Product.Attr('Scada_Telecommunications_infrastructure_review').SelectValue('Yes (One Telco involved OR infrastructure is NOT obsolete)')
    Product.Attr('Scada_Are_there_unknown_or_unfamilar_protocols').SelectValue('Yes')
    Product.Attr('Scada_Are_migration_of_existing_SCADA_System').SelectValue('Yes')
    Product.Attr('Scada_Is_SCADA_System_Interface_with_Enterprise').SelectValue('Yes')
    Product.Attr('Scada_Development_of_Custom_Standards').SelectValue('Use Existing or Honeywell Standard')
    Product.Attr('Scada_Is_Integration_Testing_Required').SelectValue('Yes')
    Product.Attr('Scada_Standard_Build_Usage_for_Integration_Test_Plan').SelectValue('Between 25% to 75% change from SB')
    Product.Attr('Scada_Standard_Build_Usage_for_FAT_Test_Plan').SelectValue('Between 25% to 75% change from SB')
    Product.Attr('Scada_Standard_Build_Usage_for_Pre_FAT_Test_Plan').SelectValue('Between 25% to 75% change from SB')
    Product.Attr('Scada_Standard_Build_Usage_for_SAT_Test_Plan').SelectValue('Between 25% to 75% change from SB')